<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Grupo Espírita Cristão a Caminho da Luz')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()
                ->appendName('description', "Grupo Espírita Cristão a Caminho da Luz - GECCAL, desde 1971.")->appendName('keywords', "Keyword")->appendName('author', "Cezar Zaleski e Reginaldo Júnior")->appendName('generator', 'HTML-KIT 292')->appendName('robots', "all")
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'href' => $this->basePath() . '/img/structure/geccal.ico'))
                ->prependStylesheet($this->basePath() . '/css/structure/layout.css')
                ->prependStylesheet($this->basePath() . '/css/structure/plugins/fixedHeader-2.1.0/css/dataTables.fixedHeader.min.css')
                ->prependStylesheet($this->basePath() . '/css/structure/plugins/sbAdmin/sb-admin.css')
                ->prependStylesheet($this->basePath() . '/css/structure/plugins/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/structure/plugins/dataTables/dataTables.bootstrap.css')
                ->prependStylesheet($this->basePath() . '/css/structure/plugins/bootstrap/bootstrap.min.css')
        ?>
    </head>
    <body>
        <?php
        echo '<div id="wrapper">';
        $usuarioAuth = new \Application\Auth\UsuarioAuth();
        echo $this->partial('layout/topo', array('usuarioAuth' => $usuarioAuth));
        echo $this->partial('layout/menu-lateral', array('usuarioAuth' => $usuarioAuth));
        echo $this->content;
        echo $this->partial('layout/modal');
        echo '</div>'
        ?>
        <?php
        echo $this->headScript()->appendFile($this->basePath() . "/js/structure/plugins/jquery/jquery-1.10.2.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/bootstrap/bootstrap.min.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/metisMenu/jquery.metisMenu.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/dataTables/jquery.dataTables.js")
                //->appendFile($this->basePath () . "/js/structure/plugins/fixedHeader-2.1.0/js/dataTables.fixedHeader.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/dataTables/dataTables.bootstrap.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/validate/jquery.validate.min.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/validate/messages_pt_BR.js")
                ->appendFile($this->basePath() . "/js/structure/plugins/sbAdmin/sb-admin.js")
                ->appendFile($this->basePath() . "/js/structure/geral.js")
                ->appendFile($this->basePath() . "/js/structure/Utils.js");
        ?>
    </body>
</html>