<!-- <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" -->
<!-- 	role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"> -->
<!-- 	<div class="modal-dialog"> -->
<!-- 		<div class="modal-content"> -->
<!-- 			<div class="modal-header"> -->
<!-- 				<button type="button" class="close" data-dismiss="modal" -->
<!-- 					aria-hidden="true">&times;</button> -->
<!-- 				<h4 class="modal-title" id="myModalLabel">Modal title</h4> -->
<!-- 			</div> -->
<!-- 			<div class="modal-body"> -->
				<!-- 				<div class="progress progress-striped active"> -->
				<!-- 					<div class="progress-bar" role="progressbar" aria-valuenow="100" -->
<!-- 				aria-valuemin="0" aria-valuemax="100" style="width: 100%"> -->
				<!-- 						<span class="sr-only">45% Complete</span> -->
				<!-- 					</div> -->
				<!-- 				</div> -->
<!-- 				<p>One fine body&hellip;</p> -->
<!-- 			</div> -->

<!-- 		</div> -->
		<!-- /.modal-content -->
<!-- 	</div> -->
	<!-- /.modal-dialog -->
<!-- </div> -->
<!-- /.modal -->

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog"
	tabindex="-1" id="myModal" class="modal fade" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button aria-hidden="true" data-dismiss="modal" class="close"
					type="button">×</button>
				<h4 id="myModalLabel" class="modal-title">Modal title</h4>
			</div>
			<div class="modal-body"></div>
<!-- 			<div class="modal-footer"> -->
<!-- 				<button data-dismiss="modal" class="btn btn-default" type="button">Close</button> -->
<!-- 				<button class="btn btn-primary" type="button">Save changes</button> -->
<!-- 			</div> -->
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>