<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="http://www.geccal.org.br/" target="_blanck">GECCAL</a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-left">
        <li class="active"><a rel="Home" href="#">Home</a></li>
        <?php echo $this->Menu()->topMenu(); ?>
    </ul>
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#">
                        <i class="fa fa-user fa-fw"></i>
                        Perfil
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-gear fa-fw"></i>
                        Configurações
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="<?php echo $this->url("logout"); ?>">
                        <i class="fa fa-sign-out fa-fw"></i>
                        Sair
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
</nav>
<!-- /.navbar-static-top -->