<?php
$form = $this->form;
$this->HtmlHelper()->setConfigFormGroup($configHtmlHelper);
$form->setAttribute('action', $this->url('home'));
?>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <ul class="page-header breadcrumb">
                <li class="active">Administração</li>
                <li><a href="/admin/funcao-atividade/listar">
                        Função/Atividade</a></li>
                <li class="active">Cadastrar</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-files-o fa-fw"></i>
                    Cadastrar Função/Atividade
                </div>
                <div class="panel-body btn btn-">
                    <?php echo $this->form()->openTag($form); ?>
                    <legend>Cadastrar Função/Atividade</legend>
                    <fieldset>
                        <?php
                        echo $this->HtmlHelper()->formGroup($this->
                                formElement($form->get('noFuncaoAtividade')),
                                $form->get('noFuncaoAtividade')->getLabel());
                        ?>
                        <?php echo $this->HtmlHelper()->formGroup(
                                $this->formElement($form->get('submit')));
                        ?>    
                    </fieldset>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>	