<?php
//$form = $this->form;
//$form->setAttribute('action', $this->url('home'));
//$form->setAttribute('class', "form");
//$form->setAttribute('id', "form");
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <ul class="page-header breadcrumb">
                <li class="active">Administração</li>
                <li><a href="/admin/funcao-atividade/listar">Função/Atividade</a></li>
                <li class="active">Editar</li>
            </ul>
        </div>

        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-files-o fa-fw"></i>
                    Editar Função/Atividade
                    <div class="pull-right">
                        <div class="btn-group">
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <?php //echo $this->form()->openTag($form); ?>
                    <legend>Editar Função/Atividade</legend>
                    <fieldset>
                        <div class="form-group">
                            <!-- 							         <label class="control-label" for="noFuncaoAtividade">Função Atividade: </label> -->
                            <?php //echo $this->formRow($form->get('noFuncaoAtividade')); ?>
                            <div class="errorInput"></div>
                        </div>
                        <?php
                        //echo $this->formRow($form->get('idFuncaoAtividade'));
                        //echo $this->formRow($form->get('submit'));
                        ?>
                    </fieldset>
                    <?php //echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>