<?php
$form = $this->form;
$this->HtmlHelper()->setConfigFormGroup($configHtmlHelper);
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <ul class="page-header breadcrumb">
                <li class="active">Administração</li>
                <li><a href="/admin/funcao-atividade/listar">Função/Atividade</a></li>
                <li class="active">Editar</li>
            </ul>
        </div>

        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-files-o fa-fw"></i>
                    Editar Função/Atividade
                    <div class="pull-right">
                        <div class="btn-group">
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <p class="requiredFild">*Campo obrigatório</p>
                    <?php echo $this->form()->openTag($form); ?>
                    <legend>Editar Função/Atividade</legend>
                    <fieldset>
                        <?php
                        echo $this->HtmlHelper()->formGroup($this->
                                formElement($form->get('noFuncaoAtividade')), 
                                $form->get('noFuncaoAtividade')->getLabel());
                        echo $this->formElement($form->get('idFuncaoAtividade'));
                        echo $this->HtmlHelper()->formGroup(
                                $this->formElement($form->get('submit')));
                        ?>
                    </fieldset>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>