<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <ul class="page-header breadcrumb">
                <li class="active">Administração</li>
                <li class="active">Função/Atividade</li>
                <li class="active">Listar</li>
            </ul>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-list-alt fa-fw"></i>
                    Listar Função Atividade
                    <div class="pull-right">
                        <div class="btn-group">
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li>
                                    <a href="#">Arquivar</a>
                                </li>
                                <li>
                                    <a href="#">Salvar</a>
                                </li>
                                <li>
                                    <a href="#">Excluir</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Encaminhar</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <a id="excluir" ><button>Excluir</button></a>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables">
                            <thead>
                                <tr>
                                    <th><input id="selectAll" type="checkbox"></th>
                                    <th class="center">Função Atividade</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->data) {
                                    foreach ($this->data as $entity) {
                                        ?>
                                        <tr class="pointer" name="selected[]" rel="<?php echo $this->Criptografia()->cripto($entity->getIdFuncaoAtividade()); ?>">
                                            <td><input type="checkbox" rel="<?php echo $this->Criptografia()->cripto($entity->getIdFuncaoAtividade()); ?>"></td>
                                            <td class="gradeA"><?php echo $entity->getNoFuncaoAtividade(); ?></td>
                                        </tr>
        <?php
    }
}
?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>