<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <ul class="page-header breadcrumb">
                <li class="active">Administração</li>
                <li class="active">Função/Atividade</li>
                <li class="active">Listar</li>
            </ul>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">

        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-list-alt fa-fw"></i>
                    Listar Função Atividade
                </div>
                <div class="col-lg-12">
                    <a id="excluir" ><button type="button" class="btn btn-primary">Excluir</button></a>
                </div>
                <div class="panel-body">


                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables">
                            <thead>
                                <tr>
                                    <th><input id="selectAll" type="checkbox"></th>
                                    <th class="center">Função Atividade</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                echo $this->partialLoop('administrator/funcao-atividade/funcao-atividade.phtml', $this->data);
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
