<?php
$form = $this->form;
$this->HtmlHelper()->setConfigFormGroup($configHtmlHelper);
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <?php
            echo $this->formElementErrors()
                    ->setMessageOpenFormat("<div class='alert 
                        alert-danger alert-dismissable'>
			<button aria-hidden='true' data-dismiss='alert' 
                        class='close' type='button'>×</button>")
                    ->setMessageSeparatorString("<br />")
                    ->setMessageCloseString('</div>')
                    ->render($form->get('noLogin'));
            ?>
            <div class="panel-heading">
                <h3 class="panel-title">Entrar</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>        
                <?php echo $this->HtmlHelper()->formGroup($this->formElement($form->get('noLogin'))); ?>
                <?php echo $this->HtmlHelper()->formGroup($this->formElement($form->get('noSenha'))); ?>
                <div class="checkbox">
                    <label>
                        <?php echo $this->formRow($form->get('stLembreme')); ?>
                    </label>
                </div>
                <?php echo $this->HtmlHelper()->formGroup($this->formElement($form->get('submit'))); ?>    
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
</div>
