<?php
$form = $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <?php
            if ($this->error) {
                echo "<div class='alert alert-danger alert-dismissable'>
				<button aria-hidden='true' data-dismiss='alert' class='close' type='button'>×</button>
				<strong>Autenticação!</strong>
				Dados de autenticação inválidos.
				</div>";
            }
            ?>
            <div class="panel-heading">
                <h3 class="panel-title">Entrar</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <fieldset>
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('noLogin')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('noSenha')); ?>
                    </div>
                    <div class="checkbox">
                        <?php echo $this->formRow($form->get('stLembreme')); ?>
                    </div>

                    <?php echo $this->formRow($form->get('submit')); ?>
                </fieldset>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
